### ISSUE TITLE
Microlathe crashes when saving image

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#131] opened 2019-01-19 18:07 UTC
Microlathe can be found here:

http://www.marshallarts.co.za/technical.htm
It crashes when clicking "save image" in the menu.

**Comment by cracyc** [comment] 2019-02-07 14:30
I can't reproduce this crash, it works fine here.

**Comment by Anixx** [comment] 2019-02-07 15:17
Well, it now works for me as well. What I did since is updated winewdm and installed it (the crash happened when winevdm was not installed).

**Comment by cracyc** [comment] 2019-02-07 18:30
If it's working then you should close this issue.

**Closed** 2019-02-07 19:01 UTC
