### ISSUE TITLE
The software developed by running windows 3.1 cannot be opened 

### ISSUE THREAD

**Issue by SkillGodAk** [otya128/winevdm#1308] opened 2023-07-31 12:53 UTC
He can install it successfully with winevdm, but the software cannot be opened after the installation is complete
Hope it helps to understand what is happening as it works successfully on Win10 x86
additional tracking
[Trace.txt](https://github.com/otya128/winevdm/files/12215142/Trace.txt)
![01](https://github.com/otya128/winevdm/assets/104513085/2814f2d0-9f71-460b-bb89-5c54df5a7c6e)

**Comment by cracyc** [comment] 2023-07-31 14:31
```
534c:43fc:trace:int:DOSVM_outport IO: 0x6c (1-byte value) to port 0x0378
534c:43fc:warn:int:DOSVM_outport Direct I/O write attempted to port 378
```
This is trying to read the parallel port.  Is it looking for a dongle?

**Comment by SkillGodAk** [comment] 2023-07-31 14:47
> ```
> 534c:43fc:trace:int:DOSVM_outport IO: 0x6c (1-byte value) to port 0x0378
> 534c:43fc:warn:int:DOSVM_outport Direct I/O write attempted to port 378
> ```
> 
> This is trying to read the parallel port. Is it looking for a dongle?

This is cracked software
Shouldn't need a dongle
My built-in NTVDM on WIN10 X86 can run
But X64 can't run

**Comment by cracyc** [comment] 2023-08-01 00:19
Try the development version and make a trace with that if it doesn't work.

**Comment by SkillGodAk** [comment] 2023-08-01 10:54
> Try the development version and make a trace with that if it doesn't work.


The latest version is still the same, I have attached the Trace
[Trace.txt](https://github.com/otya128/winevdm/files/12228104/Trace.txt)

**Comment by SkillGodAk** [comment] 2023-08-01 15:05
> Your trace is similar to the one in [#1265 (comment)](https://github.com/otya128/winevdm/issues/1265#issuecomment-1433882777) starting at line 142422 so I know that the program can work. There's nothing in the trace that shows what is going wrong though.

I tried to change the vdmdosver in otvdm.ini to 5.50, still the same error as the screenshot sent to you at the beginning

**Comment by SkillGodAk** [comment] 2023-08-02 03:24
Can you run the program I uploaded?
I put the otvdm crack file in the system directory and a new error occurred
I will show you the error screenshot and Trace
![01](https://github.com/otya128/winevdm/assets/104513085/4c192848-89fa-4203-a898-3b3f19ad5884)
[Trace.txt](https://github.com/otya128/winevdm/files/12235619/Trace.txt)

**Comment by cracyc** [comment] 2023-08-02 13:25
From that package:

> 2.Copy "enr-chs.dll" and "haspcode.dat" and "national.dll" in the CRACK package to the system folder in the system root directory.

After putting those into the winevdm windows\system directory the program works for me.

**Comment by SkillGodAk** [comment] 2023-08-02 13:55
Could it be an operating system language issue?
My operating system is Chinese, but it keeps showing that Chinese cannot be found
But it can be executed normally on win10 x86 Chinese system

**Comment by cracyc** [comment] 2023-08-02 14:11
>My operating system is Chinese, but it keeps showing that Chinese cannot be found

"Plug not Found" is the same error I get when I didn't have the crack files in the correct location.   I need a trace like the first one you posted.  The one in https://github.com/otya128/winevdm/issues/1308#issuecomment-1661431573 doesn't include the relay.

**Comment by cracyc** [comment] 2023-08-02 15:27
From the earlier trace:
```
31f0:Call KERNEL.134: GETWINDOWSDIRECTORY(12b7:c2a4,00ff) ret=11ff:14fc ds=12b7
31f0:Ret  KERNEL.134: GETWINDOWSDIRECTORY() retval=52900035 ret=11ff:14fc ds=12b7
31f0:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
31f0:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
31f0:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
31f0:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
31f0:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
31f0:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
3cc4:31f0:trace:int21:DOSVM_Int21Handler AX=4300 BX=0000 CX=417e DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003286
3cc4:31f0:trace:int21:INT21_FileAttributes GET FILE ATTRIBUTES for C:\Users\SkillGodAk\Desktop\otvdm-master-2441\WINDOWS\system.ini
3cc4:31f0:trace:int21:DOSVM_Int21Handler returning: AX=0020 BX=0000 CX=0020 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003286
3cc4:31f0:trace:int21:DOSVM_Int21Handler AX=3d00 BX=0000 CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003246
3cc4:31f0:trace:int21:INT21_CreateFile CreateFile called: function=3d, action=01, access/share=0000, create flags=4000, file=C:\Users\SkillGodAk\Desktop\otvdm-master-2441\WINDOWS\system.ini.
3cc4:31f0:trace:file:Win32HandleToDosFileHandle Got 5 for h32 000002D8
3cc4:31f0:trace:int21:INT21_CreateFile CreateFile finished: handle=5, status=1.
3cc4:31f0:trace:int21:DOSVM_Int21Handler returning: AX=0005 BX=0000 CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003246
```

From the newer one:

```
37e4:Call KERNEL.134: GETWINDOWSDIRECTORY(12b7:c2a4,00ff) ret=11ff:14fc ds=12b7
37e4:Ret  KERNEL.134: GETWINDOWSDIRECTORY() retval=549f002b ret=11ff:14fc ds=12b7
37e4:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
37e4:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
37e4:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
37e4:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
37e4:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
37e4:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
1394:37e4:trace:int21:DOSVM_Int21Handler AX=4300 BX=0000 CX=417e DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003286
1394:37e4:trace:int21:INT21_FileAttributes GET FILE ATTRIBUTES for ÈÓ\system.ini
1394:37e4:trace:int21:DOSVM_Int21Handler failed, error 123
1394:37e4:trace:int21:DOSVM_Int21Handler returning: AX=007b BX=0000 CX=417e DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003287
37e4:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
37e4:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
37e4:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7
37e4:Ret  KERNEL.36: GETCURRENTTASK() retval=11df11df ret=14b7:05dd ds=14d7
1394:37e4:trace:int21:DOSVM_Int21Handler AX=3d00 BX=062e CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003246
1394:37e4:trace:int21:INT21_CreateFile CreateFile called: function=3d, action=01, access/share=0000, create flags=4000, file=C:\Windows\System\otvdm-master-2441\WINDOWS\system.ini.
1394:37e4:trace:int21:DOSVM_Int21Handler failed, error 123
1394:37e4:trace:int21:DOSVM_Int21Handler returning: AX=007b BX=062e CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003247
```

The earlier one shows it looking for system.ini in the correct location, the newer one is wrong.  You must have broken something somewhere.  Check the WINDIR in your otvdm.ini file.

**Comment by SkillGodAk** [comment] 2023-08-02 15:51
The strange thing is that I didn't touch the otvdm.ini file in WINDIR, but I put otvdm back on the desktop and executed it again, and the error in your screenshot disappeared again.
`29e0:3cc0:trace:int21:DOSVM_Int21Handler AX=4300 BX=0000 CX=417e DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003286
29e0:3cc0:trace:int21:INT21_FileAttributes GET FILE ATTRIBUTES for C:\Users\SkillGodAk\Desktop\otvdm-master-2441\WINDOWS\system.ini
29e0:3cc0:trace:int21:DOSVM_Int21Handler returning: AX=0020 BX=0000 CX=0020 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003286
29e0:3cc0:trace:int21:DOSVM_Int21Handler AX=3d00 BX=0000 CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003246
29e0:3cc0:trace:int21:INT21_CreateFile CreateFile called: function=3d, action=01, access/share=0000, create flags=4000, file=C:\Users\SkillGodAk\Desktop\otvdm-master-2441\WINDOWS\system.ini.
29e0:3cc0:trace:file:Win32HandleToDosFileHandle Got 5 for h32 000002D8
29e0:3cc0:trace:int21:INT21_CreateFile CreateFile finished: handle=5, status=1.
29e0:3cc0:trace:int21:DOSVM_Int21Handler returning: AX=0005 BX=0000 CX=4000 DX=c2a4 SI=4001 DI=0000 DS=12b7 ES=3cd7 EFL=00003246
3cc0:Call KERNEL.36: GETCURRENTTASK() ret=14b7:05dd ds=14d7`
[Trace.txt](https://github.com/otya128/winevdm/files/12242130/Trace.txt)

**Comment by SkillGodAk** [comment] 2023-08-02 17:36
Finally succeeded, it turned out that I misplaced it

**Comment by SkillGodAk** [comment] 2023-08-02 17:48
Finally succeeded, it turned out that I misplaced it
But the opening speed is very slow, is this normal?

**Comment by cracyc** [comment] 2023-08-02 18:31
EnumFontLimitation=1 in otvdm.ini make it a lot faster but if you need all the fonts available then that won't help.

**Comment by SkillGodAk** [comment] 2023-08-02 18:53
I have tried to run with whpx vm
Some time has been shortened, but there is still a gap between the opening speed of Microsoft's NTVDM
But it's great news that it can run on X64
Thank you for spending so much time helping me
I hope that the opening speed of the later updated version can be improved

**Comment by cracyc** [comment] 2023-08-02 19:16
Since the problem is fixed you can close this report.

**Closed** 2023-08-03 04:30 UTC
