### ISSUE TITLE
Broken 256 color mode in Powerhouse and frequent hangs.

### ISSUE THREAD

**Issue by wadim-al** [otya128/winevdm#704] opened 2020-06-15 16:46 UTC
**Describe the bug**
Colors are broken in Powerhouse windows 3.1 game using 256 colors, and it tends to hangs at random times during gameplay and watching the intro.

**Expected behavior**
Colors are normal. No hangs

**Screenshots**
![otvdmw_2020-06-15_19-39-21](https://user-images.githubusercontent.com/29713984/84683493-f49dbc80-af3f-11ea-89df-dd9e504c06cb.png)
![otvdm_2020-06-15_19-26-00](https://user-images.githubusercontent.com/29713984/84682906-06329480-af3f-11ea-86e4-5fb9c832669a.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 1903
 - Version: winevdm from the "try latest" link at 15.jun.20

**Additional context**
First the app didn't want to start without 256 color mode, so I had to set this mode on the app exe.
Then the app played the intro and showed the black screen.
After I set 256 color mode on the otvdm.exe, it almost hanged on the intro, but showed damaged colors on the started game itself. Then the game was hanging at random points of time.
Game runs ok on other emulators.

[trace.txt](https://github.com/otya128/winevdm/files/4781686/trace.txt)

**Comment by cracyc** [comment] 2020-06-19 01:59
https://github.com/otya128/winevdm/pull/708 fixes the palette problems in 256 color mode

**Comment by Anixx** [comment] 2020-06-20 11:44
Pirates still has wrong palette.

**Comment by cracyc** [comment] 2020-06-20 14:04
The Pirates problem is totally different.

**Comment by wadim-al** [comment] 2020-06-20 14:17
I've found additional issues with the game. Should I update this ticket or fill new ones for speed and GUI problems?
1) Ingame dialogs are black.
2) When midi music starts or the melody changes across different screens, game hangs for several seconds.

**Comment by cracyc** [comment] 2020-06-20 14:50
> 
> 
> I've found additional issues with the game. Should I update this ticket or fill new ones for speed and GUI problems?
> 
>     1. Ingame dialogs are black.

Okay, I'll check it out.

> 
>     2. When midi music starts or the melody changes across different screens, game hangs for several seconds (shows not responding in Task Manager). The game doesn't hang if music is disabled in game's menu.

It's trying to play a wav sound but the place it looks for the file is what it thinks is a subdirectory on a cdrom (in my case D: which isn't a cdrom on my computer).  If it can't find it, it just hangs for a moment.  This also happens in ntvdm so it's not a winevdm bug.

**Comment by wadim-al** [comment] 2020-06-20 18:31
3. Also it crashes when loading a saved game with
11ff:763f	c45ef6	les     bx,[bp-0Ah]
EAX:000E,ECX:0003,EDX:141F0000,EBX:ECD8,ESP:ECD0,EBP:ECE2,ESI:002A,EDI:0000,ES:1377,CS:11FF,SS:141F,DS:141F,IP:763F,stack:002A0000,EFLAGS:00013204
vm86main(1350) #GP 0d 195c 11ff:763f 141f:ecd0
vm86main(1351) 0008:0100(base:39F0000) ESP:0000FFE8
vm86main(1352) exception
![otvdm_2020-06-20_21-30-07](https://user-images.githubusercontent.com/29713984/85209019-53e33e80-b33d-11ea-928e-fa3b24cb04f5.png)

**Comment by cracyc** [comment] 2020-06-21 03:17
https://github.com/otya128/winevdm/pull/710 fixes loading.  It still might crash under certain circumstances but it's a bug in the program that will likely also happen in ntvdm.

**Comment by wadim-al** [comment] 2020-06-21 06:29
Game loads and intro sounds started to play, but game still hangs for 3-8 seconds before midi melody starts to play.
Steps:
1. Start game
2. Open Departments menu - R&D menu item
3. Return to game from R&D screen.

Expected:
R&D screen opens in under a second.
Map is scrollable and music is playing in under a second after exiting the R&D screen.

Actual:
R&D screen opens for 5 seconds.
App hanged for 7 seconds, map is not scrollable, music is not playing after exiting R&D screen.

I have a strong feeling this is a problem with midi emulation, because disabling musing using ingame menu fixes these hangs.

Also even making the game window inactive and going back causes this delay.

**Comment by cracyc** [comment] 2020-06-21 14:13
It's sleeping in mciseq so the problem is likely http://www.virtualdub.org/blog/pivot/entry.php?id=77 which still happens in windows 10.   I was wrong about the reason but as I said I see the problem occurring in xp/ntvdm.  If you copy mciseq.dll from syswow64 to the powerhouse directory and (on windows 10) patch byte 0xb34 to 0 you'll see the midi changes don't pause anymore, there's no way outside of microsoft to properly fix it.

**Comment by wadim-al** [comment] 2020-06-21 15:24
Thanks! I confirm, patching helped.

**Comment by cracyc** [comment] 2020-06-23 17:19
https://github.com/otya128/winevdm/pull/712 mostly fixes the dialogs but since it's a bug in the program the fix might not be fully reliable.

**Comment by wadim-al** [comment] 2020-06-25 12:54
Thanks! I confirm, dialogs are not black, at least those which I've encountered so far.

FYI, this game is now playable and even the intro works better that on the real Win 3.11 PC.

This can be closed.

**Comment by cracyc** [comment] 2020-06-25 14:43
You should be able to close it yourself.

**Closed** 2020-06-25 14:44 UTC
