### ISSUE TITLE
In Civilization I, a segmentation fault appears when playing new invention sound under Win11

### ISSUE THREAD

**Issue by Anix-x** [otya128/winevdm#1035] opened 2021-10-18 19:01 UTC
On any new invention, a segmentation fault error appears, but the game can be continued.
This is under Win11

**Comment by Anixx** [comment] 2021-11-18 22:46
Checked on another installation, all the same.

**Comment by Anixx** [comment] 2022-08-16 14:22
Installed on a totally new system, with different hardware, still the same.

**Comment by Anixx** [comment] 2022-12-14 20:30
This seems to be fixed now. Please, close this report as I used another account when created it.

**Comment by Anixx** [comment] 2022-12-14 20:31
Or, possibly, the bug got fixed with windows update.

**Comment by Anixx** [comment] 2022-12-16 08:47
Oh no, I was wrong, the problem is still there. It seems it appears on any Win11 system, very much reproducible.

**Comment by cracyc** [comment] 2022-12-21 21:40
I still cant repo it.  Still need a trace,

**Comment by Anixx** [comment] 2022-12-21 22:35
Did you try Windows 11?

**Comment by cracyc** [comment] 2022-12-21 23:16
I don't have a computer right now that windows 11 can be installed on.

**Comment by Anixx** [comment] 2022-12-21 23:27
Windows 11 can be installed on any 64-bit capable system.

**Comment by cracyc** [comment] 2022-12-22 21:30
Tried a computer with windows 11. No crash.  The exact version I'm using is 1.2.0.  If yours is different then that might be why.  Otherwise, it's not getting fixed without a trace.

**Comment by Anixx** [comment] 2022-12-24 23:15
1.2.0 is version of what?

**Comment by cracyc** [comment] 2022-12-25 01:35
![Capture](https://user-images.githubusercontent.com/9255333/209454725-6f3a9a33-f6fd-40f8-a7cd-5688e2b6823b.PNG)

**Comment by Anixx** [comment] 2022-12-26 02:01
Try this one: http://www.gomerfile.net/civ-games/civwin.zip

**Closed** 2022-12-27 05:02 UTC
